### ISSUE TITLE
Using OpenGL on macOS

### ISSUE THREAD

**Issue by tanis2000** [floooh/sokol-zig#23]
Is it just me or it looks like there is no way to force sokol to use OpenGL when compiling for macOS?

**Comment by floooh** [comment]
Just define SOKOL_GLCORE33 so that it is visible in the implementation (most robust way is to pass this as compiler option, e.g. on gcc/clang ```-DSOKOL_GLCORE33``` or on MSVC ```/DSOKOL_GLCORE33```) that way, if you're using different sokol headers, all will automatically select the same backend.

**Comment by floooh** [comment]
...oops, fails on Windows... fixing...

**Comment by floooh** [comment]
Ok, Windows and Linux fixed, was a stupid oversight.

**Comment by floooh** [comment]
ah right, one sec

**Comment by tanis2000** [comment]
awesome! thank you for the quick fix! :)
