### ISSUE TITLE
EGL Support?

### ISSUE THREAD

**Issue by darltrash** [floooh/sokol-zig#31]
This issue was mostly made to point to a problem I had trying to use GLES2 with `sokol_app.h` in Linux, which would require me to link towards EGL and use the EGL X11 backend instead.

I've already made some patches and published them as pull requests, it's a bit unclean as i have mentioned in the PR, but I hope it's helpful :)

**Comment by darltrash** [comment]
https://github.com/floooh/sokol-zig/pull/30

**Comment by floooh** [comment]
CLosing this as the associated PR had been merged.
