### ISSUE TITLE
zig-devel broke some type casts in devel versions this week

### ISSUE THREAD

**Issue by jannehellsten** [floooh/sokol-zig#40]
Here's a diff against some older version of sokol for reference.

[zig-churn.txt](https://github.com/floooh/sokol-zig/files/11897488/zig-churn.txt)

(There's also some extra commas as I accidentally ran the source through `zig fmt` in VSCode.  Might not be a bad idea to use `zig fmt` for all the sources so that patches sent won't show large whitespace diffs.)

**Comment by floooh** [comment]
Could this be related to this (to be merged) PR?

https://github.com/floooh/sokol-zig/pull/39

Apparently Zig changed the type cast builtins so that the target type comes before the source (e.g.`@intToEnum` becomes `@enumFromInt`).

**Comment by nurpax** [comment]
It's related but the patch in #39 is already out of date. :) It affects things like `@intCast(dest_type, value)` that's now just `@intCast(value)` (dest type is inferred).  

See https://ziggit.dev/t/floattoint-inttofloat-gone/914 for more info.

**Comment by floooh** [comment]
Ah, inferring the dest type is a lot nicer I must say :)

**Comment by Tekkunsan** [comment]
Working on updating the PR

**Comment by floooh** [comment]
Closing this ticket, because all related PRs have been merged.
