### ISSUE TITLE
Can not compile in Windows

### ISSUE THREAD

**Issue by tuket** [floooh/sokol-zig#44]
Hi!

I don't think it's a bug in sokol, most likely it's a bug in the Zig compiler or a user error.
But I was wondering if you could help me.
Have you been able to compile any sokol app in Windows recenlty?
I'm pretty sure that I've been able to compile my sokol app at some point, but it stopped working. There seems to be an error linking `WinMain`. I have found that it might be a [more general problem](https://github.com/ziglang/zig/issues/7852). But I'm left wondering why I'm experiencing this issue now, and if other people have this issue too.

Thanks for making these awesome libraries!

**Comment by Manuzor** [comment]
I just tried `zig build` with zig v0.11.0 on the master branch of this repo and tested all the examples afterwards. Everything seems to work well.

Can you provide the source code and the version of zig you're using?

**Comment by tuket** [comment]
Thanks for trying it out!

I'm using zig v0.11.0 as well. Interesting!

Here is the project: 
[zig_sokol_test.zip](https://github.com/floooh/sokol-zig/files/12279301/zig_sokol_test.zip)

**Comment by tuket** [comment]
I tried compiling the library on it's own, and it seem to work, and I can run the samples!

The problem shows up when I try to use sokol as an external library. I have my own build.zig and I import sokol externally.
I have also tried with the new package manger approach and I get the same link error.

**Comment by floooh** [comment]
I can reproduce the problem in your project, but not in sokol-zig or my other projects, not sure what could be causing this.

Can you check if pacman.zig works for you? That should be pretty close to your use case:

https://github.com/floooh/pacman.zig

(building it works, but I just noticed that the colors are off, need to investigate this separately)

**Comment by floooh** [comment]
When I try to build your project, and look at the symbols of sokol.lib in the zig-cache, I can't find any references to main or WinMain (as it should be), e.g. what I did in a "Visual Studio command prompt" => so that Visual Studio's dumpbin tool is in the path, also 'fd' is a file-find tool installed via scoop:

```
> fd sokol.lib
zig_sokol_test\zig-cache\o\b85f443ef0ac2d82e7cac908be9a8f28\sokol.lib
> dumpbin /SYMBOLS zig_sokol_test\zig-cache\o\b85f443ef0ac2d82e7cac908be9a8f28\sokol.lib >log.txt
```

...the resulting log has all internal and external symbols in sokol.lib, and if sokol.lib wants to link with main() or WinMain() one of those symbols should be listed, which they are not though.

When you run `zig env`, what's printed? In may case:

```
C:\Users\floh\Downloads\zig_sokol_test>zig env
{
 "zig_exe": "C:\\Users\\floh\\scoop\\apps\\zig\\current\\zig.exe",
 "lib_dir": "C:\\Users\\floh\\scoop\\apps\\zig\\current\\lib",
 "std_dir": "C:\\Users\\floh\\scoop\\apps\\zig\\current\\lib\\std",
 "global_cache_dir": "C:\\Users\\floh\\AppData\\Local\\zig",
 "version": "0.11.0",
 "target": "x86_64-windows.win10_fe...win10_fe-gnu"
}
```

**Comment by Manuzor** [comment]
It looks to me like you're not specifying the root zig module anymore. I assume it got lost in translation when porting from the old build API to the new one.

```zig
const exe = b.addExecutable(.{
    .name = "zig_sokol_test",
    .target = target,
    .optimize = optimize,
    // This is missing {
    .root_source_file = .{
        .path = "src/main.zig",
    },
    // }
});

```

**Comment by floooh** [comment]
Lol yeah, that's it I guess. I just tested to remove all code, and just put an `@import("std").debug.print("Hello")` into the zig main function, and that also had the linker error.

**Comment by floooh** [comment]
Yeah confirmed that's it, putting the `.root_source_file` into build.zig makes it work. A bit strange that Zig doesn't catch that as error. I'll close the ticket, if there's anything else feel free to reopen with new details :)
