### ISSUE TITLE
Change `var`s to `const`s

### ISSUE THREAD

**Issue by noncom** [floooh/sokol-zig#49]
Though the readme officially says that the bindings are compatible with Zig 0.11, in reality they are perfectly compatible with Zig 0.12 as well, **except** having a conflict with one of the cornerstone features of that version. A conflict that is easy to fix though!

As you might know, Zig 0.12 introduces a new error about having unchanged `var`s in your code: https://ziggit.dev/t/error-local-variable-is-never-mutated/2238

So while Zig 0.12 is still in dev, fixing this problem would make them compatible without breaking anything, even if the official support still stays on Zig 0.11 for now. But it would remove the hindrance when updating from the repository. 
So it would be great if the bindings were updated to get rid of this "sloppy code".

**Comment by floooh** [comment]
I think this should be resolved by a two PRs, one is already merged:

https://github.com/floooh/sokol/pull/948

...and the other I'm going to merge now:

https://github.com/floooh/sokol-zig/pull/47
