### ISSUE TITLE
Shapes example won't work in Firefox

### ISSUE THREAD

**Issue by yanfrimmel** [floooh/sokol-zig#82]
Error when running:
`zig build run-shapes -Dtarget=wasm32-emscripten`

Error details:

`Uncaught RuntimeError: unreachable executed
    tick http://localhost:6931/shapes.js:1725`
In the function 'if' statement:

```
var _emscripten_request_animation_frame_loop = (cb, userData) => {
  function tick(timeStamp) {
    if (getWasmTableEntry(cb)(timeStamp, userData)) {
      requestAnimationFrame(tick);
    }
  }
  return requestAnimationFrame(tick);
};
```

* "clear" example did work.
* c version did work from site.
* Tested with Firefox.

**Comment by yanfrimmel** [comment]
Problem is in these lines:

`    var vertices: [6 * 1024]sshape.Vertex = undefined;
    var indices: [16 * 1024]u16 = undefined;`

That creates segmentation fault, Those array are too large, consider using heap allocations.

**Comment by floooh** [comment]
Ah, the Emscripten stack size reduction strikes again :/ (a little while ago, Emscripten reduced the default stack size to 64 KBytes).

I fixed the problem like this instead:

https://github.com/floooh/sokol-zig/commit/c5bdb504ea562eaa2c7d8c655e20467a1e385e3a
