### ISSUE TITLE
Bug with emscripten/js glue ? 

### ISSUE THREAD

**Issue by Gandalf-Le-Dev** [floooh/sokol-zig#84]
### Problem

I am using the default sokol shell for my emscripten build and when I log things, whatever the level of the log they are outputted as errors. From what I see in the generated JS and html files there is a differentiation between errors and non errors print but for a reason I ignore everything comes out as an error. 

### How to reproduce 

Add a log to any example `std.log.info("init from std log", .{});`
Run with `zig build run -Dtarget=wasm32-emscripten`
Open your browser console and you will see an error with you log content even if it is just an info log

### Quick fix: 
edit the generated html file 
```diff
<script>
var Module = { 
preRun: [],
postRun: [], 
print: function (n) { n = Array.prototype.slice.call(arguments).join(" "), console.log(n) }, 
- printErr: function (n) { n = Array.prototype.slice.call(arguments).join(" "), console.error(n) }, 
+ printErr: function (n) { n = Array.prototype.slice.call(arguments).join(" "), console.log(n) }, 
canvas: document.getElementById("canvas"), 
setStatus: function (n) { }, monitorRunDependencies: function (n) { } }; window.onerror = function () { console.log("onerror: " + event.message) }
</script>
```

### Question 

Is this a bug or am I logging incorrectly or misunderstanding something ?

**Comment by floooh** [comment]
Looks to me like the Zig logging system generally prints to stderr (e.g. the Emscripten print and printErr hooks are for output to stdout and stderr). Logging to stderr instead of stdout isn't unusual to separate regular program output from logging messages.

I'll probably change the shell.html printErr to smth like to make clear that this is output on stderr and not regular stdout output:

```ks
printErr: function (n) { n = Array.prototype.slice.call(arguments).join(" "), console.log(`[stderr]: ${n}`) }, 
```

**Comment by Gandalf-Le-Dev** [comment]
Thanks a lot for the details 😄
